#This is an example configuration file for ubrn. You can copy this file to ubrn.config.yaml and modify it as needed.
rust:
  repo: https://github.com/LiamWhelan1/audio-analyzer-rs.git
  branch: master
  manifestPath: rust/audio-engine/Cargo.toml

bindings:
  cpp: cpp/bindings
  ts: ts/bindings

android:
  apiLevel: 26 #important for android audio

